homepage: "https://github.com/NguyenHien-8/tcq-network-protocol"
language: go
primary_contact: "trannguyenhien29085@gmail.com"
main_repo: "https://github.com/NguyenHien-8/tcq-network-protocol"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
